version: '3'

services:
  server:
    container_name: server
    image: redditlite-server-img
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always